# Generated by Django 2.0.2 on 2019-05-29 07:08

import backend.core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_category', verbose_name='imagen')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoryequipment_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoryequipment_modified', to=settings.AUTH_USER_MODEL)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_padre', to='resource.CategoryEquipment')),
            ],
            options={
                'verbose_name': 'categoría de equipo',
                'verbose_name_plural': 'categorías de equipos',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CategoryManpower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_category', verbose_name='imagen')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorymanpower_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorymanpower_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'categoría de mano de obra',
                'verbose_name_plural': 'categorías de mano de obra',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CategoryMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_category', verbose_name='imagen')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorymaterial_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorymaterial_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'categoría de material',
                'verbose_name_plural': 'categorías de materiales',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('code', backend.core.utils.CharNullField(blank=True, max_length=30, null=True, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('unit', models.CharField(blank=True, max_length=15, null=True, verbose_name='unidad de costo')),
                ('currency', models.CharField(choices=[('S', 'S/'), ('D', '$')], default='D', max_length=1, verbose_name='moneda')),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='costo unitario')),
                ('pull_in_new_budget', models.BooleanField(default=False)),
                ('hours_equipment_operation', models.DecimalField(decimal_places=6, default=8, max_digits=15, verbose_name='horas de operación del equipo')),
                ('potencia', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='potencia del equipo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment', verbose_name='image')),
                ('has_combustible', models.BooleanField(default=False)),
                ('tipo_combustible', models.CharField(blank=True, choices=[('GO', 'GasOil'), ('GS', 'Gasolina')], max_length=2, null=True, verbose_name='tipo de combustible')),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.CategoryEquipment')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'equipo',
                'verbose_name_plural': 'equipos',
            },
        ),
        migrations.CreateModel(
            name='Manpower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('code', backend.core.utils.CharNullField(blank=True, max_length=30, null=True, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('unit', models.CharField(blank=True, max_length=15, null=True, verbose_name='unidad de costo')),
                ('currency', models.CharField(choices=[('S', 'S/'), ('D', '$')], default='D', max_length=1, verbose_name='moneda')),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='costo unitario')),
                ('pull_in_new_budget', models.BooleanField(default=False)),
                ('sueldo_bruto', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='sueldo bruto')),
                ('type_cost', models.CharField(choices=[('D', 'DIRECTO'), ('I', 'INDIRECTO')], default='D', max_length=1, verbose_name='tipo de costo')),
                ('allows_ratio', models.PositiveIntegerField(default=1, verbose_name='Permite coeficiente?')),
                ('tipo_regimen', models.CharField(choices=[('C', 'COMÚN'), ('V', 'CIVIL')], default='C', max_length=1, verbose_name='tipo de regimen')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mano de obra',
                'verbose_name_plural': 'manos de obra',
                'ordering': ('code', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('code', backend.core.utils.CharNullField(blank=True, max_length=30, null=True, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('unit', models.CharField(blank=True, max_length=15, null=True, verbose_name='unidad de costo')),
                ('currency', models.CharField(choices=[('S', 'S/'), ('D', '$')], default='D', max_length=1, verbose_name='moneda')),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='costo unitario')),
                ('pull_in_new_budget', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='material', verbose_name='image')),
                ('class_cost', models.CharField(choices=[('S', 'Estandar'), ('M', 'Medico'), ('W', 'Taller'), ('O', 'Operativo'), ('V', 'Varios'), ('I', 'Insumo médico'), ('E', 'EPP')], default='S', max_length=1, verbose_name='clase de costo')),
                ('is_subcontract', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.CategoryMaterial')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiales',
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Subcontract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('code', backend.core.utils.CharNullField(blank=True, max_length=30, null=True, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('unit', models.CharField(blank=True, max_length=15, null=True, verbose_name='unidad de costo')),
                ('currency', models.CharField(choices=[('S', 'S/'), ('D', '$')], default='D', max_length=1, verbose_name='moneda')),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='costo unitario')),
                ('pull_in_new_budget', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontract_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontract_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subcontrato',
                'verbose_name_plural': 'subcontratos',
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('moneda', models.CharField(choices=[('S', 'S/'), ('D', '$')], default='D', max_length=1, verbose_name='moneda')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacuna_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacuna_modified', to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(blank=True, limit_choices_to={'grupo': 'UBC'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_vacuna', to='core.GruposVarios', verbose_name='ubicacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VacunaDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=6, default=1, max_digits=15, verbose_name='cantidad')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='observacion')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacunadetail_created', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_vacunas_budget', to='resource.Material', verbose_name='vacunas material')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacunadetail_modified', to=settings.AUTH_USER_MODEL)),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_vacuna', to='resource.Vacuna', verbose_name='Vacuna')),
            ],
            options={
                'ordering': ('material',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='vacunadetail',
            unique_together={('vacuna', 'material')},
        ),
    ]
