# coding=utf-8

from __future__ import unicode_literals


CURRENCY_SOL = 'S'
CURRENCY_DOLLAR = 'D'
CURRENCIES = (
    (CURRENCY_SOL, 'S/'),
    (CURRENCY_DOLLAR, '$'),
)
CURRENCIES_DEFAULT = CURRENCY_DOLLAR


MONEDA_SOLES = 'S'
MONEDA_DOLARES = 'D'
MONEDAS = (
    (MONEDA_SOLES, 'S/'),
    (MONEDA_DOLARES, '$'),
)
MONEDAS_DEFAULT = MONEDA_DOLARES

TYPE_COST_DIRECT = "D"
TYPE_COST_INDIRECT = "I"
TYPE_COST = (
    (TYPE_COST_DIRECT, "DIRECTO"),
    (TYPE_COST_INDIRECT, "INDIRECTO"),
)
TYPE_COST_DEFAULT = TYPE_COST_DIRECT

TYPE_MATERIAL_STANDARD = "S"
TYPE_MATERIAL_MEDICAL = "M"
TYPE_MATERIAL_WORKSHOP = "W"
TYPE_MATERIAL_OPERATIVE = "O"
TYPE_MATERIAL_VARIOUS = "V"
TYPE_MATERIAL_INSUMO_MEDICO = "I"
TYPE_MATERIAL_EPP = "E"
TYPE_MATERIAL = (
    (TYPE_MATERIAL_STANDARD, "Estandar"),
    (TYPE_MATERIAL_MEDICAL, "Medico"),
    (TYPE_MATERIAL_WORKSHOP, "Taller"),
    (TYPE_MATERIAL_OPERATIVE, "Operativo"),
    (TYPE_MATERIAL_VARIOUS, "Varios"),
    (TYPE_MATERIAL_INSUMO_MEDICO, "Insumo médico"),
    (TYPE_MATERIAL_EPP, "EPP")
)
TYPE_MATERIAL_DEFAULT = TYPE_MATERIAL_STANDARD

CLASS_OVERHEAD_MEDICAL = "M"
CLASS_OVERHEAD_MEDICAL = "M"
CLASS_OVERHEAD_WORKSHOP = "W"
CLASS_OVERHEAD_OPERATIVE = "O"
CLASS_OVERHEAD_VARIOUS = "V"
CLASS_OVERHEAD_INSUMO_MEDICO = "I"
CLASS_OVERHEAD_EPP = "E"
CLASS_OVERHEAD = (
    (CLASS_OVERHEAD_MEDICAL, "Medico"),
    (CLASS_OVERHEAD_WORKSHOP, "Taller"),
    (CLASS_OVERHEAD_OPERATIVE, "Operativo"),
    (CLASS_OVERHEAD_VARIOUS, "Varios"),
    (CLASS_OVERHEAD_INSUMO_MEDICO, "Insumo médico"),
    (CLASS_OVERHEAD_EPP, "EPP")
)
CLASS_OVERHEAD_DEFAULT = CLASS_OVERHEAD_VARIOUS

ESTADO_PRESUPUESTO_CANCELADO = "CA"
ESTADO_PRESUPUESTO_FALTA_FECHA = "FF"
ESTADO_PRESUPUESTO_FECHA_POR_CONFIRMAR = "PC"
ESTADO_PRESUPUESTO_PENDIENTE = "PE"
ESTADO_PRESUPUESTO_SUPERADO = "SU"
ESTADO_PRESUPUESTO_NEW = "NW"
ESTADOS_PRESUPUESTO = (
    (ESTADO_PRESUPUESTO_CANCELADO, "CANCELADO"),
    (ESTADO_PRESUPUESTO_FALTA_FECHA, "FALTA FECHA"),
    (ESTADO_PRESUPUESTO_FECHA_POR_CONFIRMAR, "FECHA POR CONFIRMAR"),
    (ESTADO_PRESUPUESTO_PENDIENTE, "PENDIENTE"),
    (ESTADO_PRESUPUESTO_SUPERADO, "SUPERADO"),
    (ESTADO_PRESUPUESTO_NEW, "NUEVO"),
)
ESTADOS_PRESUPUESTO_DEFAULT = ESTADO_PRESUPUESTO_NEW

TIPO_EMPRESA_NATURAL = 'N'
TIPO_EMPRESA_JURIDICA = 'J'
TIPOS_EMPRESA = (
    (TIPO_EMPRESA_NATURAL, 'Natural'),
    (TIPO_EMPRESA_JURIDICA, 'Jurídica'),
)
TIPOS_EMPRESA_DEFAULT = TIPO_EMPRESA_JURIDICA

MODELO_PRESUPUESTO = "PP"
MODELO_MATERIALES = "MT"
MODELO_MANO_OBRA = "MO"

MODELOS = (
    (MODELO_PRESUPUESTO, "Presupuesto"),
    (MODELO_MATERIALES, "Materiales"),
    (MODELO_MANO_OBRA, "Mano de obra"),
)

ESTADO_PROYECTO_ADJUDICADO = "AD"
ESTADO_PROYECTO_EN_PROCESO = "EP"
ESTADO_PROYECTO_CERRADO = "CE"
ESTADO_PROYECTO_CANCELADO = "CA"
ESTADOS_PROYECTO = (
    (ESTADO_PROYECTO_ADJUDICADO, "Adjudicado"),
    (ESTADO_PROYECTO_EN_PROCESO, "En Proceso"),
    (ESTADO_PROYECTO_CERRADO, "Cerrado"),
    (ESTADO_PROYECTO_CANCELADO, "Cancelado")
)
ESTADOS_PROYECTO_DEFAULT = ESTADO_PROYECTO_EN_PROCESO

MEDIO_CONTACTO_TELEFONO = 0
MEDIO_CONTACTO_CELULAR = 1
MEDIO_CONTACTO_EMAIL = 2
MEDIO_CONTACTO_OTROS = 3

MEDIOS_CONTACTO = (
    (MEDIO_CONTACTO_TELEFONO, 'Teléfono'),
    (MEDIO_CONTACTO_CELULAR, 'Celular'),
    (MEDIO_CONTACTO_EMAIL, 'Correo'),
    (MEDIO_CONTACTO_OTROS, 'Otros'),
)
MEDIOS_CONTACTO_DEFAULT = MEDIO_CONTACTO_TELEFONO

GRUPO_CATEGORIA_TRABAJADOR = "CTR"
GRUPO_TIPO_EPP = "TTR"
GRUPO_UBICACION = "UBC"
GRUPO_MONEDA = "MON"
GRUPO_REGIMEN = "REG"
GRUPOS_VARIOS = (
    (GRUPO_CATEGORIA_TRABAJADOR, "CATEGORIA TRABAJADOR"),
    (GRUPO_TIPO_EPP, "TIPO DE EPP"),
    (GRUPO_UBICACION, "UBICACIÓN"),
    (GRUPO_MONEDA, "MONEDA"),
    (GRUPO_REGIMEN, "REGIMEN")
)

TIPO_REGIMEN_COMUN = "C"
TIPO_REGIMEN_CIVIL = "V"
TIPOS_REGIMEN = (
    (TIPO_REGIMEN_COMUN, 'COMÚN'),
    (TIPO_REGIMEN_CIVIL, 'CIVIL'),
)
TIPOS_REGIMEN_DEFAULT = TIPO_REGIMEN_COMUN
COMBUSTIBLE = (
    ("GO","GasOil"),
    ("GS","Gasolina"),
)
REGIMEN = {
    "21x7;1": 2,
    "21x7;2": 3,
    "21x7;3": 5,
    "28x7;1": 2,
    "28x7;2": 3,
    "28x7;3": 4,
    "28x7;4": 6,
    "28x7;5": 7,
    "28x7;6": 8,
    "28x7;7": 10,
    "28x7;8": 11,
    "28x7;9": 12,
    "28x7;10": 14,
    "28x7;11": 15,
    "28x7;12": 16,
    "28x7;13": 18,
    "28x7;14": 19,
    "28x7;15": 20,
    "28x7;16": 22,
    "28x7;17": 23,
    "28x7;18": 24,
    "30x0;1": 1,
    "30x0;2": 2,
    "30x0;3": 3,
    "30x0;4": 4,
    "30x0;5": 5,
    "30x0;6": 6,
    "30x0;7": 7,
    "30x0;8": 8,
    "30x0;9": 9,
    "30x0;10": 10,
    "30x0;11": 11,
    "30x0;12": 12,
    "30x0;13": 13,
    "30x0;14": 14,
    "30x0;15": 15,
    "30x0;16": 16,
    "30x0;17": 17,
    "30x0;18": 18,
}
