# Generated by Django 2.0.2 on 2019-05-29 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('core', '0001_initial'),
        ('resource', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbudget',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskbudget_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskbudget',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskbudget_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcontracttask',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontracttask_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcontracttask',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontracttask_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcontracttask',
            name='subcontract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontracts_subcontract_task', to='resource.Subcontract', verbose_name='subcontract'),
        ),
        migrations.AddField(
            model_name='subcontracttask',
            name='subcontract_budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontracts_budget_subcontract_task', to='budget.SubcontractBudget'),
        ),
        migrations.AddField(
            model_name='subcontracttask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_subcontract_task', to='budget.TaskBudget', verbose_name='tarea'),
        ),
        migrations.AddField(
            model_name='subcontractbudget',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontracts_budget', to='budget.Budget', verbose_name='Presupuesto'),
        ),
        migrations.AddField(
            model_name='subcontractbudget',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontractbudget_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcontractbudget',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontractbudget_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcontractbudget',
            name='subcontract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontracts_subcontract_budget', to='resource.Subcontract', verbose_name='subcontrato'),
        ),
        migrations.AddField(
            model_name='memberbudget',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_budget', to='budget.Budget', verbose_name='presupuesto'),
        ),
        migrations.AddField(
            model_name='memberbudget',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberbudget_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memberbudget',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberbudget_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memberbudget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_member_budget', to=settings.AUTH_USER_MODEL, verbose_name='miembro'),
        ),
        migrations.AddField(
            model_name='materialtask',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialtask_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialtask',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_material_task', to='resource.Material', verbose_name='material'),
        ),
        migrations.AddField(
            model_name='materialtask',
            name='material_budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_budget_material_task', to='budget.MaterialBudget'),
        ),
        migrations.AddField(
            model_name='materialtask',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialtask_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_material_task', to='budget.TaskBudget', verbose_name='tarea'),
        ),
        migrations.AddField(
            model_name='materialbudget',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_budget', to='budget.Budget', verbose_name='Presupuesto'),
        ),
        migrations.AddField(
            model_name='materialbudget',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialbudget_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialbudget',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_material_budget', to='resource.Material', verbose_name='material'),
        ),
        migrations.AddField(
            model_name='materialbudget',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialbudget_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manpowertask',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manpowertask_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manpowertask',
            name='manpower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manpowers_manpower_task', to='resource.Manpower', verbose_name='mano de obra'),
        ),
        migrations.AddField(
            model_name='manpowertask',
            name='manpower_budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manpowers_budget_manpower_task', to='budget.ManpowerBudget'),
        ),
        migrations.AddField(
            model_name='manpowertask',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manpowertask_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manpowertask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_manpower_task', to='budget.TaskBudget', verbose_name='tarea'),
        ),
        migrations.AddField(
            model_name='manpowerbudget',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manpowers_budget', to='budget.Budget', verbose_name='Presupuesto'),
        ),
        migrations.AddField(
            model_name='manpowerbudget',
            name='certificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.CertificacionBudget', verbose_name='certificacion'),
        ),
        migrations.AddField(
            model_name='manpowerbudget',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manpowerbudget_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manpowerbudget',
            name='manpower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manpowers_manpower_budget', to='resource.Manpower', verbose_name='mano de obra'),
        ),
        migrations.AddField(
            model_name='manpowerbudget',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manpowerbudget_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manpowerbudget',
            name='tipo_epp',
            field=models.ForeignKey(blank=True, limit_choices_to={'grupo': 'TTR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_epps_manpower_grupo', to='core.GruposVarios', verbose_name='tipo de epp'),
        ),
        migrations.AddField(
            model_name='equipmenttask',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipmenttask_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmenttask',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments_equipment_task', to='resource.Equipment', verbose_name='equipment'),
        ),
        migrations.AddField(
            model_name='equipmenttask',
            name='equipment_budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments_budget_equipment_task', to='budget.EquipmentBudget'),
        ),
        migrations.AddField(
            model_name='equipmenttask',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipmenttask_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmenttask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_equipment_task', to='budget.TaskBudget', verbose_name='tarea'),
        ),
        migrations.AddField(
            model_name='equipmentbudget',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments_budget', to='budget.Budget', verbose_name='Presupuesto'),
        ),
        migrations.AddField(
            model_name='equipmentbudget',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.CategoryEquipment'),
        ),
        migrations.AddField(
            model_name='equipmentbudget',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipmentbudget_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentbudget',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments_equipment_budget', to='resource.Equipment', verbose_name='equipo'),
        ),
        migrations.AddField(
            model_name='equipmentbudget',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipmentbudget_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eppbudgetdetail',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eppbudgetdetail_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eppbudgetdetail',
            name='epp_budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_epps_budget', to='budget.EPPBudget', verbose_name='prepuesto de epp'),
        ),
        migrations.AddField(
            model_name='eppbudgetdetail',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_epps_budget', to='budget.MaterialBudget', verbose_name='epp material'),
        ),
        migrations.AddField(
            model_name='eppbudgetdetail',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eppbudgetdetail_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eppbudget',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epps_budget', to='budget.Budget', verbose_name='presupuesto'),
        ),
        migrations.AddField(
            model_name='eppbudget',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eppbudget_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eppbudget',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eppbudget_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eppbudget',
            name='tipo_epp',
            field=models.ForeignKey(limit_choices_to={'grupo': 'TTR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_epps_grupo', to='core.GruposVarios', verbose_name='tipo de epp'),
        ),
        migrations.AddField(
            model_name='certificacionbudget',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificaciones_budget', to='budget.Budget', verbose_name='presupuesto'),
        ),
        migrations.AddField(
            model_name='certificacionbudget',
            name='certificado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificacion_certificado', to='core.Certificado', verbose_name='certificado'),
        ),
        migrations.AddField(
            model_name='certificacionbudget',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificacionbudget_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificacionbudget',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificacionbudget_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='client.Client', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='budget',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='ubicacion',
            field=models.ForeignKey(blank=True, limit_choices_to={'grupo': 'UBC'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion_presupuesto', to='core.GruposVarios', verbose_name='ubicacion'),
        ),
        migrations.AddField(
            model_name='budget',
            name='vacunas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacunas_budget', to='resource.Vacuna', verbose_name='vacunas'),
        ),
        migrations.AlterUniqueTogether(
            name='subcontractbudget',
            unique_together={('budget', 'subcontract')},
        ),
        migrations.AlterUniqueTogether(
            name='materialbudget',
            unique_together={('budget', 'material')},
        ),
        migrations.AlterUniqueTogether(
            name='manpowerbudget',
            unique_together={('budget', 'manpower')},
        ),
        migrations.AlterUniqueTogether(
            name='equipmentbudget',
            unique_together={('budget', 'equipment')},
        ),
        migrations.AlterUniqueTogether(
            name='eppbudgetdetail',
            unique_together={('epp_budget', 'material')},
        ),
        migrations.AlterUniqueTogether(
            name='eppbudget',
            unique_together={('budget', 'tipo_epp')},
        ),
        migrations.AlterUniqueTogether(
            name='certificacionbudget',
            unique_together={('budget', 'certificado')},
        ),
    ]
