# Generated by Django 2.0.2 on 2019-05-29 07:08

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='dirección de correo')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='nombres')),
                ('lastname', models.CharField(blank=True, max_length=50, null=True, verbose_name='apellidos')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_user', verbose_name='Foto')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='importe')),
                ('currency', models.CharField(choices=[('S', 'S/'), ('D', '$')], default='D', max_length=1, verbose_name='moneda')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'certificado',
                'verbose_name_plural': 'certificados',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Correlative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('PP', 'Presupuesto'), ('MT', 'Materiales'), ('MO', 'Mano de obra')], max_length=3, verbose_name='modelo')),
                ('prefix', models.CharField(blank=True, max_length=10, null=True, verbose_name='prefijo')),
                ('current_number', models.IntegerField(default=0, verbose_name='número actual')),
            ],
            options={
                'verbose_name': 'correlativo',
                'verbose_name_plural': 'correlativos',
            },
        ),
        migrations.CreateModel(
            name='GruposVarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('grupo', models.CharField(choices=[('CTR', 'CATEGORIA TRABAJADOR'), ('TTR', 'TIPO DE EPP'), ('UBC', 'UBICACIÓN'), ('MON', 'MONEDA'), ('REG', 'REGIMEN')], max_length=3, verbose_name='grupo')),
                ('activo', models.BooleanField(default=True)),
                ('predeterminado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'grupo varios',
                'verbose_name_plural': 'grupos varios',
                'ordering': ('grupo', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('sueldo', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='sueldo')),
                ('currency', models.CharField(choices=[('S', 'S/'), ('D', '$')], default='D', max_length=1, verbose_name='moneda')),
                ('activo', models.BooleanField(default=True)),
                ('categoria_trabajador', models.ForeignKey(limit_choices_to={'activo': True, 'grupo': 'CTR'}, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_regimen', to='core.GruposVarios', verbose_name='categoria')),
                ('regimen', models.ForeignKey(limit_choices_to={'activo': True, 'grupo': 'REG'}, on_delete=django.db.models.deletion.CASCADE, related_name='grupos_regimen', to='core.GruposVarios', verbose_name='regimen')),
            ],
            options={
                'verbose_name': 'regimen',
                'verbose_name_plural': 'regimenes',
                'ordering': ('regimen', 'categoria_trabajador'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='regimen',
            unique_together={('regimen', 'categoria_trabajador')},
        ),
    ]
